version: "3"
services:
  mysql-server:
    image: "mysql:5.7"
    ports:
      - 9090:3306
    environment:
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./backup:/app
  node-server:
    restart: always
    depends_on:
      - mysql-server
    build:
      context: "./Backend"
      dockerfile: "./Dockerfile"
    volumes:
      - /app/node_modules
      - ./Backend:/app
    ports: 
      - 3000:3000