export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';