export const SET_CONTACTS = 'SET_CONTACTS'
export const UPDATE_PENDING_APPOINTMENT = 'UPDATE_PENDING_APPOINTMENT'
export const REMOVE_ALL_PENDING_APPOINTMENT = 'REMOVE_ALL_PENDING_APPOINTMENT'
export const SET_LOADING_APPOINTMENTS = 'SET_LOADING_APPOINTMENTS'
export const ADD_APPOINTMENTS = 'ADD_APPOINTMENTS'



// SAGAS
export const CREATE_NEW_APPOINTMENT = 'CREATE_NEW_APPOINTMENT'
export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS'




export const MAX_PENDING_APPOINTMENTS = 3