export const SET_CONTACTS = 'SET_CONTACTS'
export const UPDATE_PENDING_APPOINTMENT = 'UPDATE_PENDING_APPOINTMENT'
export const REMOVE_ALL_PENDING_APPOINTMENT = 'REMOVE_ALL_PENDING_APPOINTMENT'



// SAGAS
export const CREATE_NEW_APPOINTMENT = 'CREATE_NEW_APPOINTMENT'




export const MAX_PENDING_APPOINTMENTS = 3